# IF table attr
PART_MIG_T1 = "PARTCD_MSTR_PR"
PART_MIG_T1_C1 = "PR_ITEM_NAME"
PART_MIG_T1_C2 = "PR_PROC_LINE_CODE"
PART_MIG_T1_C3 = "PR_FEED_LINE_CODE"

PART_MIG_T2 = "PROCFROW_PR"
PART_MIG_T2_C1 = "PR_PROC_CODE"
PART_MIG_T2_C2 = "PR_PROC_LINE_CODE"

PROC_MIG_T1 = "PROCFROW_PR"
PROC_MIG_T1_C1 = "PR_PROC_LINE_CODE"
PROC_MIG_T1_C2 = "PR_PROC_ORDER"
PROC_MIG_T1_C3 = "PR_PROC_CODE"

# planner table attr
# PART_MSTR
PART_MSTR = "PART_MSTR"
PART_MSTR_CPART = "CPART"
PART_MSTR_CPMID = "CPMID"
PART_MSTR_CPMIDX = "CPMIDX"
PART_MSTR_CPARTN = "CPARTN"
PART_MSTR_CPEGFLG = "CPEGFLG"
PART_MSTR_CDSPFLG = "CDSPFLG"
PART_MSTR_NDSPODR = "NDSPODR"
PART_MSTR_CSITECD = "CSITECD"
PART_MSTR_CPARTCD = "CPARTCD"
PART_MSTR_CPROCCD = "CPROCCD"
PART_MSTR_CSITETCD = "CSITETCD"

# PART_INF
PART_INF = "PART_INF"
PART_INF_CPART = "CPART"
PART_INF_NAHEAD = "NAHEAD"
PART_INF_CSAFE = "CSAFE"
PART_INF_NSAFSTKL = "NSAFSTKL"
PART_INF_NSTRSTKL = "NSTRSTKL"
PART_INF_CNSTN = "CNSTN"
PART_INF_CASAP = "CASAP"
PART_INF_NEXECPEN = "NEXECPEN"
PART_INF_NSTRT = "NSTRT"
PART_INF_NPIPELEN = "NPIPELEN"
PART_INF_NBASE = "NBASE"
PART_INF_NDTERM = "NDTERM"
PART_INF_NATSPRIOR = "NATSPRIOR"
PART_INF_CCNSFLG = "CCNSFLG"
PART_INF_CIGNORLOT = "CIGNORLOT"
PART_INF_CPRMIGNORLOT = "CPRMIGNORLOT"
PART_INF_CNOYIELD = "CNOYIELD"


# PROC_DIM
PROC_DIM = "PROC_DIM"
PROC_DIM_CPROCCD = "CPROCCD"
PROC_DIM_CPROCNM = "CPROCNM"
PROC_DIM_CLEVEL1CD = "CLEVEL1CD"
PROC_DIM_CLEVEL1NM = "CLEVEL1NM"
PROC_DIM_CLEVEL2CD = "CLEVEL2CD"
PROC_DIM_CLEVEL2NM = "CLEVEL2NM"
PROC_DIM_CLEVEL3CD = "CLEVEL3CD"
PROC_DIM_CLEVEL3NM = "CLEVEL3NM"
PROC_DIM_CLEVEL4CD = "CLEVEL4CD"
PROC_DIM_CLEVEL4NM = "CLEVEL4NM"


# each flagment attr
ATTR_BLANK = ""
ATTR_FLG_P = "P"
ATTR_FLG_Y = "Y"
ATTR_FLG_N = "N"
ATTR_VALUE_MINUS1 = "-1"
ATTR_VALUE_0 = "0"
ATTR_VALUE_9999 = "9999"
